export const AVAILABLE_ACTIONS = {
    FETCH_AVAILABILITY: 'FETCH_AVAILABILITY',
    NEW_AVAILABILITY: 'NEW_AVAILABILITY',
    // POST_AVAILABILITY: 'POST_AVAILABILITY',
    STORE_AVAILABILITY: 'STORE_AVAILABILITY',
    // REMOVE_AVAILABILITY: 'REMOVE_AVAILABILITY',
    // EDIT_AVAILABILITY: 'EDIT_AVAILABILITY',
    STORE_UNAVAILABILITY: 'STORE_UNAVAILABILITY',
    FETCH_UNAVAILABILITY: 'FETCH_UNAVAILABILITY',
    RESET_NEW_AVAILABILITY: 'RESET_NEW_AVAILABILITY',
}