export const UNAVAILABLE_ACTIONS = {
    NEW_AVAILABILITY: 'NEW_APPOINTMENT',
    // POST_AVAILABILITY: 'POST_AVAILABILITY',
    // STORE_AVAILABILITY: 'STORE_AVAILABILITY',
    // REMOVE_AVAILABILITY: 'REMOVE_AVAILABILITY',
    // EDIT_AVAILABILITY: 'EDIT_AVAILABILITY',
    STORE_UNAVAILABILITY: 'STORE_UNAVAILABILITY',
    FETCH_UNAVAILABILITY: 'FETCH_UNAVAILABILITY',
    RESET_NEW_AVAILABILITY: 'RESET_NEW_APPOINTMENT',
    FETCH_ESTIMATE_DURATION: 'FETCH_ESTIMATE_DURATION',
    POST_NEW_AVAILABILITY_DATA: 'POST_NEW_AVAILABILITY_DATA',
}