export const UNAVAILABLE_ACTIONS = {
    NEW_AVAILABILITY: 'NEW_APPOINTMENT',
    STORE_UNAVAILABILITY: 'STORE_UNAVAILABILITY',
    FETCH_UNAVAILABILITY: 'FETCH_UNAVAILABILITY',
    RESET_NEW_AVAILABILITY: 'RESET_NEW_APPOINTMENT',
    FETCH_ESTIMATE_DURATION: 'FETCH_ESTIMATE_DURATION',
    POST_NEW_AVAILABILITY_DATA: 'POST_NEW_AVAILABILITY_DATA',
}